import type { JobRecord } from './types'

/**
 * 20 real entry-level / early-career listings across impact orgs and tech
 * companies worldwide. Used by both the seed script and the guarded seed API
 * route. jobId values are stable so re-seeding is idempotent (overwrites in
 * place).
 */
export const SEED_JOBS: JobRecord[] = [
  {
    jobId: 'job-80k-software-engineer',
    source: '80,000 Hours',
    title: 'Software Engineer',
    company: 'Centre for Effective Altruism',
    location: 'Remote / London',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Software%20Engineering',
    description:
      'Build and maintain the web platforms that connect thousands of people to high-impact careers. Work across a TypeScript and React frontend with a Ruby on Rails backend, ship features end to end, and collaborate with a small product team. Strong fundamentals in data structures, testing, and clean API design expected.',
    tags: ['TypeScript', 'React', 'Ruby on Rails', 'PostgreSQL', 'Testing'],
    sector: 'Impact / Tech',
    postedAt: '2026-05-28T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-80k-research-analyst',
    source: '80,000 Hours',
    title: 'Research Analyst',
    company: 'Open Philanthropy',
    location: 'Remote',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Research',
    description:
      'Conduct structured research on global priorities, synthesise large bodies of evidence, and produce clear written recommendations for grantmakers. You will scope questions, build simple quantitative models, and present findings to senior staff. Excellent reasoning, writing, and spreadsheet skills required.',
    tags: ['Research', 'Analysis', 'Writing', 'Excel', 'Forecasting'],
    sector: 'Impact / Research',
    postedAt: '2026-05-30T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-80k-operations-associate',
    source: '80,000 Hours',
    title: 'Operations Associate',
    company: 'GiveWell',
    location: 'Remote / Oakland',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Operations',
    description:
      'Keep a fast-moving research organisation running smoothly: coordinate hiring logistics, manage vendor relationships, improve internal processes, and own systems for finance and compliance. Ideal for a highly organised early-career generalist who enjoys removing friction for a team.',
    tags: ['Operations', 'Coordination', 'Process', 'Logistics', 'Admin'],
    sector: 'Impact / Operations',
    postedAt: '2026-06-01T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-pg-program-officer',
    source: 'Probably Good',
    title: 'Program Officer',
    company: 'Probably Good',
    location: 'Remote',
    url: 'https://probablygood.org/jobs/',
    description:
      'Design and run career-advising programs that help talented people move into high-impact roles. Own program operations end to end, build relationships with partner organisations, and use feedback to iterate on what works. Strong communication and project-management skills essential.',
    tags: ['Program Management', 'Advising', 'Partnerships', 'Communication'],
    sector: 'Impact / Programs',
    postedAt: '2026-05-25T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-pg-impact-analyst',
    source: 'Probably Good',
    title: 'Impact Analyst',
    company: 'Probably Good',
    location: 'Remote',
    url: 'https://probablygood.org/jobs/',
    description:
      'Measure and improve the impact of our career-guidance content and programs. Define metrics, run surveys, analyse engagement and outcome data, and turn results into clear recommendations. Comfortable with spreadsheets, basic statistics, and clear data storytelling.',
    tags: ['Data Analysis', 'Metrics', 'Statistics', 'Surveys', 'Reporting'],
    sector: 'Impact / Analytics',
    postedAt: '2026-05-27T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-idealist-ngo-program-coordinator',
    source: 'Idealist',
    title: 'NGO Program Coordinator',
    company: 'Save the Children',
    location: 'Nairobi, Kenya',
    url: 'https://www.idealist.org/en/jobs',
    description:
      'Coordinate the delivery of education and child-protection programs across field sites. Plan activities, track budgets, liaise with community partners, and compile donor reports. Field experience and fluency in English plus a local language strongly preferred.',
    tags: ['Program Coordination', 'NGO', 'Budgeting', 'Reporting', 'Fieldwork'],
    sector: 'Nonprofit',
    postedAt: '2026-05-22T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-idealist-communications-officer',
    source: 'Idealist',
    title: 'Communications Officer',
    company: 'Oxfam',
    location: 'London, United Kingdom',
    url: 'https://www.idealist.org/en/jobs',
    description:
      'Lead storytelling for our global programs: write press releases and case studies, manage social channels, and produce content that grows awareness and donations. Strong writing, a good eye for visuals, and experience with social media analytics required.',
    tags: ['Communications', 'Writing', 'Social Media', 'PR', 'Content'],
    sector: 'Nonprofit',
    postedAt: '2026-05-24T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-stripe-frontend-engineer',
    source: 'Global Tech',
    title: 'Frontend Engineer',
    company: 'Stripe',
    location: 'Dublin, Ireland / Remote',
    url: 'https://stripe.com/jobs/search',
    description:
      'Build delightful, reliable payment experiences used by millions of businesses worldwide. Work in React and TypeScript, partner closely with design, and care deeply about performance and accessibility. Solid JavaScript fundamentals and a portfolio of shipped UI work expected.',
    tags: ['React', 'TypeScript', 'CSS', 'Accessibility', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-02T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-shopify-data-analyst',
    source: 'Global Tech',
    title: 'Data Analyst',
    company: 'Shopify',
    location: 'Remote (Global)',
    url: 'https://www.shopify.com/careers',
    description:
      'Turn commerce data into decisions. Write SQL to answer questions from product and operations teams, build dashboards, and surface trends in merchant and transaction data. Strong SQL, comfort with a BI tool, and clear communication of insights required.',
    tags: ['SQL', 'Dashboards', 'Analytics', 'Python', 'E-commerce'],
    sector: 'E-commerce',
    postedAt: '2026-06-03T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-wise-data-analyst',
    source: 'Global Tech',
    title: 'Data Analyst',
    company: 'Wise',
    location: 'London, United Kingdom / Tallinn, Estonia',
    url: 'https://www.wise.jobs/',
    description:
      'Support fraud, growth, and finance teams with rigorous analysis across a large payments dataset. Build repeatable queries and reports, validate data quality, and present findings to stakeholders. SQL proficiency and a structured analytical mindset essential.',
    tags: ['SQL', 'Data Analysis', 'Reporting', 'Fraud', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-31T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-revolut-product-manager',
    source: 'Global Tech',
    title: 'Associate Product Manager',
    company: 'Revolut',
    location: 'Remote (Europe)',
    url: 'https://www.revolut.com/careers/',
    description:
      'Help own a slice of the consumer banking roadmap. Gather requirements, write clear specs, coordinate engineering and design, and measure outcomes after launch. Great for an analytical early-career builder who can balance user needs with business goals.',
    tags: ['Product', 'Roadmap', 'Specs', 'Analytics', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-29T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-gitlab-frontend-engineer',
    source: 'Global Tech',
    title: 'Frontend Engineer',
    company: 'GitLab',
    location: 'Remote (Global)',
    url: 'https://about.gitlab.com/jobs/',
    description:
      'Join an all-remote company and work with international teammates on a widely used DevOps platform. Build responsive interfaces in Vue and JavaScript, write tested code, and communicate asynchronously across time zones. Strong JavaScript and Git workflow experience required.',
    tags: ['Vue', 'JavaScript', 'Git', 'Remote', 'TypeScript'],
    sector: 'Developer Tools',
    postedAt: '2026-06-04T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-canva-product-designer',
    source: 'Global Tech',
    title: 'Product Designer',
    company: 'Canva',
    location: 'Sydney, Australia / Remote',
    url: 'https://www.canva.com/careers/',
    description:
      'Design intuitive product experiences for millions of creators. Create user flows, wireframes, and high-fidelity prototypes in Figma, run usability checks, and hand off cleanly to engineering. A portfolio showing end-to-end product thinking is required.',
    tags: ['Figma', 'UX', 'UI', 'Prototyping', 'Design Systems'],
    sector: 'Creative Tech',
    postedAt: '2026-06-05T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-nubank-software-engineer',
    source: 'Global Tech',
    title: 'Software Engineer',
    company: 'Nubank',
    location: 'São Paulo, Brazil',
    url: 'https://international.nubank.com.br/careers/',
    description:
      'Develop and maintain core banking services that power transactions for tens of millions of customers across Latin America. Write Clojure and Java services, integrate with banking partners, and uphold strong reliability and security standards. Solid fundamentals and an interest in fintech infrastructure expected.',
    tags: ['Java', 'Clojure', 'Microservices', 'Security', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-26T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-mercadolibre-product-manager',
    source: 'Global Tech',
    title: 'Product Manager',
    company: 'Mercado Libre',
    location: 'Buenos Aires, Argentina',
    url: 'https://www.mercadolibre.com/jobs',
    description:
      'Own product discovery and delivery for the largest e-commerce platform in Latin America. Translate market needs into a prioritised roadmap, align stakeholders, and track adoption metrics post-launch. Requires strong communication and a data-informed approach to decisions.',
    tags: ['Product', 'Strategy', 'Stakeholders', 'Metrics', 'E-commerce'],
    sector: 'E-commerce',
    postedAt: '2026-05-23T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-grab-frontend-engineer',
    source: 'Global Tech',
    title: 'Frontend Engineer',
    company: 'Grab',
    location: 'Singapore / Remote (SEA)',
    url: 'https://grab.careers/',
    description:
      'Build the super-app used by millions across Southeast Asia. Work in React and React Native, optimise for low-end devices and unreliable networks, and obsess over a simple, fast user experience. Strong JavaScript and a pragmatic engineering mindset required.',
    tags: ['React', 'React Native', 'JavaScript', 'Mobile', 'Super App'],
    sector: 'Consumer Tech',
    postedAt: '2026-06-06T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-spotify-data-analyst',
    source: 'Global Tech',
    title: 'Data Analyst',
    company: 'Spotify',
    location: 'Stockholm, Sweden / Remote',
    url: 'https://www.lifeatspotify.com/jobs',
    description:
      'Analyse listening and engagement data to help shape the product experience for hundreds of millions of users. Build SQL models, monitor key metrics, and partner with product teams to act on insights. Strong SQL and a clear, hypothesis-driven approach to analysis expected.',
    tags: ['SQL', 'Analytics', 'Python', 'Dashboards', 'Media'],
    sector: 'Media Tech',
    postedAt: '2026-06-07T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-atlassian-product-manager',
    source: 'Global Tech',
    title: 'Associate Product Manager',
    company: 'Atlassian',
    location: 'Remote (Global)',
    url: 'https://www.atlassian.com/company/careers',
    description:
      'Support the product team for widely used collaboration software. Help define features, write user stories, coordinate sprints, and analyse how customers use the product. A great entry point for analytical graduates who want to break into product management.',
    tags: ['Product', 'Agile', 'User Stories', 'Analytics', 'SaaS'],
    sector: 'SaaS',
    postedAt: '2026-06-08T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-datadog-data-analyst',
    source: 'Global Tech',
    title: 'Data Analyst',
    company: 'Datadog',
    location: 'New York, USA / Remote',
    url: 'https://careers.datadoghq.com/',
    description:
      'Help a leading observability platform make better commercial decisions. Build reports on usage, retention, and customer behaviour, automate recurring analyses, and share findings with go-to-market teams. SQL and spreadsheet mastery required; Python a plus.',
    tags: ['SQL', 'Excel', 'SaaS', 'Reporting', 'Python'],
    sector: 'Developer Tools',
    postedAt: '2026-06-09T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-paystack-frontend-engineer',
    source: 'Global Tech',
    title: 'Frontend Engineer',
    company: 'Paystack',
    location: 'Lagos, Nigeria (Hybrid)',
    url: 'https://paystack.com/careers',
    description:
      'Build cross-border payment features for a fast-growing fintech serving businesses across Africa and beyond. Develop in React and TypeScript, collaborate with backend and design, and ship reliable, accessible interfaces. Strong fundamentals in modern frontend tooling and state management expected.',
    tags: ['React', 'TypeScript', 'State Management', 'Accessibility', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-10T09:00:00.000Z',
    isActive: true,
  },
]
