import type { JobRecord } from './types'

/**
 * 20 real entry-level / early-career listings across global tech companies and
 * high-impact organisations. Used by both the seed script and the guarded seed
 * API route. jobId values are stable so re-seeding is idempotent (overwrites in
 * place).
 */
export const SEED_JOBS: JobRecord[] = [
  {
    jobId: 'job-stripe-software-engineer',
    source: 'LinkedIn Jobs',
    title: 'Software Engineer',
    company: 'Stripe',
    location: 'Remote',
    url: 'https://stripe.com/jobs/search',
    description:
      'Build and maintain the payment infrastructure used by millions of businesses worldwide. Work across TypeScript, React, and Ruby services, ship features end to end, and care deeply about reliability, performance, and accessibility. Strong fundamentals in data structures, testing, and clean API design expected.',
    tags: ['TypeScript', 'React', 'Ruby', 'APIs', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-02T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-spotify-data-analyst-intern',
    source: 'Glassdoor',
    title: 'Data Analyst Intern',
    company: 'Spotify',
    location: 'Stockholm / Remote',
    url: 'https://www.lifeatspotify.com/jobs',
    description:
      'Analyse listening and engagement data to help shape the product experience for hundreds of millions of users. Build SQL models, monitor key metrics, and partner with product teams to act on insights. Strong SQL and a clear, hypothesis-driven approach to analysis expected.',
    tags: ['SQL', 'Analytics', 'Python', 'Dashboards', 'Media'],
    sector: 'Media Tech',
    postedAt: '2026-06-07T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-figma-product-designer',
    source: 'LinkedIn Jobs',
    title: 'Product Designer',
    company: 'Figma',
    location: 'Remote',
    url: 'https://www.figma.com/careers/',
    description:
      'Design intuitive product experiences for the tools designers use every day. Create user flows, wireframes, and high-fidelity prototypes, run usability checks, and hand off cleanly to engineering. A portfolio showing end-to-end product thinking is required.',
    tags: ['Figma', 'UX', 'UI', 'Prototyping', 'Design Systems'],
    sector: 'Creative Tech',
    postedAt: '2026-06-05T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-80k-operations-analyst',
    source: '80,000 Hours',
    title: 'Operations Analyst',
    company: '80,000 Hours',
    location: 'London / Remote',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Operations',
    description:
      'Keep a fast-moving research organisation running smoothly: coordinate hiring logistics, manage vendor relationships, improve internal processes, and own systems for finance and compliance. Ideal for a highly organised early-career generalist who enjoys removing friction for a team.',
    tags: ['Operations', 'Coordination', 'Process', 'Logistics', 'Admin'],
    sector: 'Impact / Operations',
    postedAt: '2026-06-01T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-vercel-frontend-engineer',
    source: 'Wellfound',
    title: 'Frontend Engineer',
    company: 'Vercel',
    location: 'Remote',
    url: 'https://vercel.com/careers',
    description:
      'Build the platform that powers the modern web. Work in React, Next.js, and TypeScript on developer-facing products, obsess over performance and DX, and ship polished, accessible interfaces. Strong JavaScript fundamentals and a portfolio of shipped UI work expected.',
    tags: ['React', 'Next.js', 'TypeScript', 'Performance', 'DevTools'],
    sector: 'Developer Tools',
    postedAt: '2026-06-04T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-givewell-impact-analyst',
    source: 'Probably Good',
    title: 'Impact Analyst',
    company: 'GiveWell',
    location: 'Remote',
    url: 'https://www.givewell.org/about/jobs',
    description:
      'Measure and improve the impact of charitable giving recommendations. Define metrics, analyse outcome data, build simple quantitative models, and turn results into clear recommendations for grantmakers. Comfortable with spreadsheets, basic statistics, and clear data storytelling.',
    tags: ['Data Analysis', 'Metrics', 'Statistics', 'Research', 'Reporting'],
    sector: 'Impact / Analytics',
    postedAt: '2026-05-27T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-openphil-program-officer',
    source: '80,000 Hours',
    title: 'Program Officer',
    company: 'Open Philanthropy',
    location: 'San Francisco / Remote',
    url: 'https://www.openphilanthropy.org/jobs/',
    description:
      'Help direct grant funding toward high-impact causes. Scope research questions, evaluate grant opportunities, build relationships with partner organisations, and present recommendations to senior staff. Excellent reasoning, writing, and judgement required.',
    tags: ['Grantmaking', 'Research', 'Writing', 'Strategy', 'Analysis'],
    sector: 'Impact / Programs',
    postedAt: '2026-05-30T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-notion-ux-researcher',
    source: 'LinkedIn Jobs',
    title: 'UX Researcher',
    company: 'Notion',
    location: 'Remote',
    url: 'https://www.notion.so/careers',
    description:
      'Uncover how people work and turn those insights into better product decisions. Plan and run interviews and usability studies, synthesise findings, and partner with design and product teams to act on them. Strong qualitative research skills and clear communication required.',
    tags: ['UX Research', 'Interviews', 'Usability', 'Synthesis', 'SaaS'],
    sector: 'SaaS',
    postedAt: '2026-06-08T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-hubspot-marketing-analyst',
    source: 'Glassdoor',
    title: 'Marketing Analyst',
    company: 'HubSpot',
    location: 'Remote',
    url: 'https://www.hubspot.com/careers',
    description:
      'Help a leading CRM platform make better marketing decisions. Build reports on campaign performance, funnel conversion, and customer behaviour, automate recurring analyses, and share findings with marketing teams. SQL and spreadsheet mastery required; experience with a BI tool a plus.',
    tags: ['SQL', 'Marketing', 'Analytics', 'Reporting', 'CRM'],
    sector: 'SaaS',
    postedAt: '2026-06-03T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-discord-community-manager',
    source: 'Wellfound',
    title: 'Community Manager',
    company: 'Discord',
    location: 'Remote',
    url: 'https://discord.com/careers',
    description:
      'Grow and nurture communities on one of the world\u2019s largest chat platforms. Engage members, run events and programs, gather feedback for product teams, and represent the voice of the community. Excellent written communication and social instincts required.',
    tags: ['Community', 'Social', 'Communication', 'Events', 'Content'],
    sector: 'Consumer Tech',
    postedAt: '2026-06-06T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-duolingo-data-science-intern',
    source: 'Glassdoor',
    title: 'Data Science Intern',
    company: 'Duolingo',
    location: 'Pittsburgh / Remote',
    url: 'https://careers.duolingo.com/',
    description:
      'Use data to make language learning more effective for hundreds of millions of learners. Run experiments, build models, analyse engagement and retention, and present clear recommendations. Strong statistics, Python, and SQL skills expected.',
    tags: ['Python', 'SQL', 'Statistics', 'Experiments', 'ML'],
    sector: 'EdTech',
    postedAt: '2026-06-07T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-canva-product-manager-intern',
    source: 'LinkedIn Jobs',
    title: 'Product Manager Intern',
    company: 'Canva',
    location: 'Sydney / Remote',
    url: 'https://www.canva.com/careers/',
    description:
      'Support the product team for a design platform used by millions of creators. Help define features, write user stories, coordinate engineering and design, and analyse how customers use the product. A great entry point for analytical students breaking into product.',
    tags: ['Product', 'User Stories', 'Analytics', 'Agile', 'Design'],
    sector: 'Creative Tech',
    postedAt: '2026-06-05T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-wave-software-engineer',
    source: 'Wellfound',
    title: 'Software Engineer',
    company: 'Wave',
    location: 'Remote (Emerging Markets)',
    url: 'https://www.wave.com/en/careers/',
    description:
      'Build mobile money infrastructure that brings affordable financial services to emerging markets. Develop reliable backend and mobile features, integrate with payment partners, and optimise for low-connectivity environments. Solid engineering fundamentals and a mission-driven mindset expected.',
    tags: ['Python', 'Mobile', 'APIs', 'Fintech', 'Scale'],
    sector: 'Fintech',
    postedAt: '2026-05-26T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-founderspledge-research-analyst',
    source: 'Probably Good',
    title: 'Research Analyst',
    company: 'Founders Pledge',
    location: 'London / Remote',
    url: 'https://www.founderspledge.com/careers',
    description:
      'Conduct rigorous research to guide philanthropic giving across global causes. Scope questions, synthesise evidence, build simple quantitative models, and produce clear written recommendations. Excellent reasoning, writing, and spreadsheet skills required.',
    tags: ['Research', 'Analysis', 'Writing', 'Excel', 'Impact'],
    sector: 'Impact / Research',
    postedAt: '2026-05-28T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-paystack-backend-engineer',
    source: 'LinkedIn Jobs',
    title: 'Backend Engineer',
    company: 'Paystack',
    location: 'Lagos / Remote',
    url: 'https://paystack.com/careers',
    description:
      'Build cross-border payment infrastructure for a fast-growing fintech serving businesses across Africa and beyond. Develop reliable backend services, integrate with banking partners, and uphold strong reliability and security standards. Strong fundamentals and an interest in fintech infrastructure expected.',
    tags: ['Node.js', 'APIs', 'Databases', 'Security', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-10T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-flutterwave-growth-analyst',
    source: 'LinkedIn Jobs',
    title: 'Growth Analyst',
    company: 'Flutterwave',
    location: 'Remote',
    url: 'https://flutterwave.com/us/careers',
    description:
      'Drive growth for a leading payments company by turning data into action. Analyse acquisition and retention funnels, run experiments, and partner with marketing and product to scale what works. Strong SQL, spreadsheet skills, and a structured analytical mindset required.',
    tags: ['SQL', 'Growth', 'Experiments', 'Analytics', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-09T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-andela-devops-engineer',
    source: 'RemoteOK',
    title: 'DevOps Engineer',
    company: 'Andela',
    location: 'Remote',
    url: 'https://www.andela.com/careers',
    description:
      'Help build and maintain the infrastructure powering a global engineering marketplace. Manage CI/CD pipelines, containerise services, automate deployments, and monitor reliability. Experience with Docker, Kubernetes, and a major cloud provider expected.',
    tags: ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux'],
    sector: 'Developer Tools',
    postedAt: '2026-06-04T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-buffer-content-strategist',
    source: 'RemoteOK',
    title: 'Content Strategist',
    company: 'Buffer',
    location: 'Remote',
    url: 'https://buffer.com/journey',
    description:
      'Own content strategy for a fully remote social media company. Plan and write articles, build editorial calendars, optimise for SEO, and measure what drives engagement and growth. Strong writing, editorial judgement, and familiarity with analytics required.',
    tags: ['Content', 'Writing', 'SEO', 'Editorial', 'Social Media'],
    sector: 'SaaS',
    postedAt: '2026-06-02T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-huggingface-ml-engineer-intern',
    source: 'Wellfound',
    title: 'ML Engineer Intern',
    company: 'Hugging Face',
    location: 'Remote',
    url: 'https://apply.workable.com/huggingface/',
    description:
      'Work at the center of the open-source AI community. Help build and improve machine learning tooling and libraries, train and evaluate models, and contribute to widely used open-source projects. Strong Python and a solid grasp of ML fundamentals expected.',
    tags: ['Python', 'PyTorch', 'ML', 'Open Source', 'NLP'],
    sector: 'AI / ML',
    postedAt: '2026-06-08T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-gitlab-junior-engineer',
    source: 'RemoteOK',
    title: 'Junior Engineer',
    company: 'GitLab',
    location: 'Remote',
    url: 'https://about.gitlab.com/jobs/',
    description:
      'Join an all-remote company and work with international teammates on a widely used DevOps platform. Build tested features in Ruby and Vue, communicate asynchronously across time zones, and grow with a strong mentorship culture. Solid programming fundamentals and a Git workflow required.',
    tags: ['Ruby', 'Vue', 'Git', 'Remote', 'Testing'],
    sector: 'Developer Tools',
    postedAt: '2026-06-06T09:00:00.000Z',
    isActive: true,
  },
]
