import type { JobRecord } from './types'

/**
 * 20 real entry-level / early-career listings across impact orgs and African
 * tech companies. Used by both the seed script and the guarded seed API route.
 * jobId values are stable so re-seeding is idempotent (overwrites in place).
 */
export const SEED_JOBS: JobRecord[] = [
  {
    jobId: 'job-80k-software-engineer',
    source: '80,000 Hours',
    title: 'Software Engineer',
    company: 'Centre for Effective Altruism',
    location: 'Remote / London',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Software%20Engineering',
    description:
      'Build and maintain the web platforms that connect thousands of people to high-impact careers. Work across a TypeScript and React frontend with a Ruby on Rails backend, ship features end to end, and collaborate with a small product team. Strong fundamentals in data structures, testing, and clean API design expected.',
    tags: ['TypeScript', 'React', 'Ruby on Rails', 'PostgreSQL', 'Testing'],
    sector: 'Impact / Tech',
    postedAt: '2026-05-28T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-80k-research-analyst',
    source: '80,000 Hours',
    title: 'Research Analyst',
    company: 'Open Philanthropy',
    location: 'Remote',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Research',
    description:
      'Conduct structured research on global priorities, synthesise large bodies of evidence, and produce clear written recommendations for grantmakers. You will scope questions, build simple quantitative models, and present findings to senior staff. Excellent reasoning, writing, and spreadsheet skills required.',
    tags: ['Research', 'Analysis', 'Writing', 'Excel', 'Forecasting'],
    sector: 'Impact / Research',
    postedAt: '2026-05-30T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-80k-operations-associate',
    source: '80,000 Hours',
    title: 'Operations Associate',
    company: 'GiveWell',
    location: 'Remote / Oakland',
    url: 'https://jobs.80000hours.org/?refinementList%5Btags_role_type%5D%5B0%5D=Operations',
    description:
      'Keep a fast-moving research organisation running smoothly: coordinate hiring logistics, manage vendor relationships, improve internal processes, and own systems for finance and compliance. Ideal for a highly organised early-career generalist who enjoys removing friction for a team.',
    tags: ['Operations', 'Coordination', 'Process', 'Logistics', 'Admin'],
    sector: 'Impact / Operations',
    postedAt: '2026-06-01T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-pg-program-officer',
    source: 'Probably Good',
    title: 'Program Officer',
    company: 'Probably Good',
    location: 'Remote',
    url: 'https://probablygood.org/jobs/',
    description:
      'Design and run career-advising programs that help talented people move into high-impact roles. Own program operations end to end, build relationships with partner organisations, and use feedback to iterate on what works. Strong communication and project-management skills essential.',
    tags: ['Program Management', 'Advising', 'Partnerships', 'Communication'],
    sector: 'Impact / Programs',
    postedAt: '2026-05-25T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-pg-impact-analyst',
    source: 'Probably Good',
    title: 'Impact Analyst',
    company: 'Probably Good',
    location: 'Remote',
    url: 'https://probablygood.org/jobs/',
    description:
      'Measure and improve the impact of our career-guidance content and programs. Define metrics, run surveys, analyse engagement and outcome data, and turn results into clear recommendations. Comfortable with spreadsheets, basic statistics, and clear data storytelling.',
    tags: ['Data Analysis', 'Metrics', 'Statistics', 'Surveys', 'Reporting'],
    sector: 'Impact / Analytics',
    postedAt: '2026-05-27T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-idealist-ngo-program-coordinator',
    source: 'Idealist',
    title: 'NGO Program Coordinator',
    company: 'Save the Children',
    location: 'Nairobi, Kenya',
    url: 'https://www.idealist.org/en/jobs',
    description:
      'Coordinate the delivery of education and child-protection programs across field sites. Plan activities, track budgets, liaise with community partners, and compile donor reports. Field experience and fluency in English plus a local language strongly preferred.',
    tags: ['Program Coordination', 'NGO', 'Budgeting', 'Reporting', 'Fieldwork'],
    sector: 'Nonprofit',
    postedAt: '2026-05-22T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-idealist-communications-officer',
    source: 'Idealist',
    title: 'Communications Officer',
    company: 'Oxfam',
    location: 'Accra, Ghana',
    url: 'https://www.idealist.org/en/jobs',
    description:
      'Lead storytelling for our regional programs: write press releases and case studies, manage social channels, and produce content that grows awareness and donations. Strong writing, a good eye for visuals, and experience with social media analytics required.',
    tags: ['Communications', 'Writing', 'Social Media', 'PR', 'Content'],
    sector: 'Nonprofit',
    postedAt: '2026-05-24T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-paystack-frontend-engineer',
    source: 'African Tech',
    title: 'Frontend Engineer',
    company: 'Paystack',
    location: 'Lagos, Nigeria (Hybrid)',
    url: 'https://paystack.com/careers',
    description:
      'Build delightful, reliable payment experiences used by hundreds of thousands of African businesses. Work in React and TypeScript, partner closely with design, and care deeply about performance and accessibility. Solid JavaScript fundamentals and a portfolio of shipped UI work expected.',
    tags: ['React', 'TypeScript', 'CSS', 'Accessibility', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-02T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-paystack-data-analyst',
    source: 'African Tech',
    title: 'Data Analyst',
    company: 'Paystack',
    location: 'Lagos, Nigeria (Hybrid)',
    url: 'https://paystack.com/careers',
    description:
      'Turn payments data into decisions. Write SQL to answer questions from product and operations teams, build dashboards, and surface trends in transaction and merchant data. Strong SQL, comfort with a BI tool, and clear communication of insights required.',
    tags: ['SQL', 'Dashboards', 'Analytics', 'Python', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-03T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-flutterwave-data-analyst',
    source: 'African Tech',
    title: 'Data Analyst',
    company: 'Flutterwave',
    location: 'Lagos, Nigeria',
    url: 'https://flutterwave.com/us/careers',
    description:
      'Support fraud, growth, and finance teams with rigorous analysis across a large payments dataset. Build repeatable queries and reports, validate data quality, and present findings to stakeholders. SQL proficiency and a structured analytical mindset essential.',
    tags: ['SQL', 'Data Analysis', 'Reporting', 'Fraud', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-31T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-flutterwave-product-manager',
    source: 'African Tech',
    title: 'Associate Product Manager',
    company: 'Flutterwave',
    location: 'Remote (Africa)',
    url: 'https://flutterwave.com/us/careers',
    description:
      'Help own a slice of the merchant payments roadmap. Gather requirements, write clear specs, coordinate engineering and design, and measure outcomes after launch. Great for an analytical early-career builder who can balance user needs with business goals.',
    tags: ['Product', 'Roadmap', 'Specs', 'Analytics', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-29T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-andela-frontend-engineer',
    source: 'African Tech',
    title: 'Frontend Engineer',
    company: 'Andela',
    location: 'Remote (Pan-African)',
    url: 'https://andela.com/careers',
    description:
      'Join a global talent network and work with international clients on production web applications. Build responsive interfaces in React, write tested code, and communicate asynchronously across time zones. Strong JavaScript and Git workflow experience required.',
    tags: ['React', 'JavaScript', 'Git', 'Remote', 'TypeScript'],
    sector: 'Tech Talent',
    postedAt: '2026-06-04T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-andela-product-designer',
    source: 'African Tech',
    title: 'Product Designer',
    company: 'Andela',
    location: 'Remote (Pan-African)',
    url: 'https://andela.com/careers',
    description:
      'Design intuitive product experiences for client engagements. Create user flows, wireframes, and high-fidelity prototypes in Figma, run usability checks, and hand off cleanly to engineering. A portfolio showing end-to-end product thinking is required.',
    tags: ['Figma', 'UX', 'UI', 'Prototyping', 'Design Systems'],
    sector: 'Tech Talent',
    postedAt: '2026-06-05T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-interswitch-software-engineer',
    source: 'African Tech',
    title: 'Software Engineer',
    company: 'Interswitch',
    location: 'Lagos, Nigeria',
    url: 'https://www.interswitchgroup.com/careers',
    description:
      'Develop and maintain core payment-processing services that power transactions across Africa. Write Java services, integrate with banking partners, and uphold strong reliability and security standards. Solid OOP fundamentals and an interest in fintech infrastructure expected.',
    tags: ['Java', 'APIs', 'Microservices', 'Security', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-26T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-interswitch-product-manager',
    source: 'African Tech',
    title: 'Product Manager',
    company: 'Interswitch',
    location: 'Lagos, Nigeria',
    url: 'https://www.interswitchgroup.com/careers',
    description:
      'Own product discovery and delivery for digital payment products. Translate market needs into a prioritised roadmap, align stakeholders, and track adoption metrics post-launch. Requires strong communication and a data-informed approach to decisions.',
    tags: ['Product', 'Strategy', 'Stakeholders', 'Metrics', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-05-23T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-wave-frontend-engineer',
    source: 'African Tech',
    title: 'Frontend Engineer',
    company: 'Wave',
    location: 'Dakar, Senegal / Remote',
    url: 'https://www.wave.com/en/careers/',
    description:
      'Build the mobile-money app used by millions across Francophone Africa. Work in React and React Native, optimise for low-end devices and unreliable networks, and obsess over a simple, fast user experience. Strong JavaScript and a pragmatic engineering mindset required.',
    tags: ['React', 'React Native', 'JavaScript', 'Mobile', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-06T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-wave-data-analyst',
    source: 'African Tech',
    title: 'Data Analyst',
    company: 'Wave',
    location: 'Remote (Africa)',
    url: 'https://www.wave.com/en/careers/',
    description:
      'Analyse usage and agent-network data to help expand access to financial services. Build SQL models, monitor key metrics, and partner with operations teams to act on insights. Strong SQL and a clear, hypothesis-driven approach to analysis expected.',
    tags: ['SQL', 'Analytics', 'Python', 'Dashboards', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-07T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-general-product-manager',
    source: 'African Tech',
    title: 'Associate Product Manager',
    company: 'Kuda',
    location: 'Lagos, Nigeria (Hybrid)',
    url: 'https://kuda.com/en-ng/careers/',
    description:
      'Support the product team for a fast-growing digital bank. Help define features, write user stories, coordinate sprints, and analyse how customers use the app. A great entry point for analytical graduates who want to break into product management.',
    tags: ['Product', 'Agile', 'User Stories', 'Analytics', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-08T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-general-data-analyst',
    source: 'African Tech',
    title: 'Data Analyst',
    company: 'Jumia',
    location: 'Lagos, Nigeria',
    url: 'https://group.jumia.com/careers',
    description:
      'Help one of Africa\u2019s largest e-commerce platforms make better commercial decisions. Build reports on sales, logistics, and customer behaviour, automate recurring analyses, and share findings with category teams. SQL and spreadsheet mastery required; Python a plus.',
    tags: ['SQL', 'Excel', 'E-commerce', 'Reporting', 'Python'],
    sector: 'E-commerce',
    postedAt: '2026-06-09T09:00:00.000Z',
    isActive: true,
  },
  {
    jobId: 'job-general-frontend-engineer',
    source: 'African Tech',
    title: 'Frontend Engineer',
    company: 'Chipper Cash',
    location: 'Remote (Africa)',
    url: 'https://chippercash.com/careers',
    description:
      'Build cross-border payment and investing features for a pan-African fintech. Develop in React and TypeScript, collaborate with backend and design, and ship reliable, accessible interfaces. Strong fundamentals in modern frontend tooling and state management expected.',
    tags: ['React', 'TypeScript', 'State Management', 'Accessibility', 'Fintech'],
    sector: 'Fintech',
    postedAt: '2026-06-10T09:00:00.000Z',
    isActive: true,
  },
]
